### ISSUE TITLE
Use faces and customization interface

### ISSUE THREAD

**Issue by mrkkrp** [hagleitn/speed-type#11]
I think it would an improvement if this package defined dedicated customization group via `defgroup`. Then you can put there all the variables that are supposed to be configurable and users will be able to configure `speed-type` via <kbd>M-x customize-group speed-type RET</kbd>.

Also, you can define special faces for correctly entered text and incorrectly entered text. I think it's a good idea to highlight statistics and use shadowed text for info text. For these tasks more faces can be defined, they will be configurable too and accessible via customization interface.

What do you think about these ideas?

**Comment by parkouss** [comment]
Hey @mrkkrp, I love the ideas! Since this github repo is not active anymore, I am the new maintainer of the speed-type package (which is available on melpa): https://github.com/parkouss/speed-type.

I just started to implement some of what you proposed, that is a speed-type group and customizable faces for correctly typed and mistaken characters. I am not sure to understand the other ideas, feel free to open an issue on the new repo, or create a pull request against it. thanks :)

**Comment by mrkkrp** [comment]
It's great the package has a new maintainer, I'll keep an eye on the new repo :-)
